### PR TITLE
Update Offset

### PR DESCRIPTION
**Pull request by H4vC**

### CODE REVIEW

**Comment by vmv** [comment]
ok, done. Ty,

**Comment by H4vC** [comment]
Np should I also do a build and send that up or just not even worry about it.

**Comment by vmv** [comment]
Can you integrate the design part too ?
Shouldn't take more then 10-30 min :)
Let's make ppl happy :D

**Comment by H4vC** [comment]
I'll compile from your branch and send you a dll link I guess or do you mean re-integrate design into the H4vC branch ?

**Comment by vmv** [comment]
I have all up to date, don't need for a compiled version. Also i have the ItemFilter parser from smad, all is good on my side. I was asking for full merge to have the new design on the Master.

**Comment by H4vC** [comment]
Sure I'll go look at it.

**Comment by H4vC** [comment]
Send  a pull request and i'll merge up the stuff.

**Comment by vmv** [comment]
Ok,i will try that.

**Pull request merged**
